services:
  whisperhub:
    build:
      context: ./whisperhub
      dockerfile: Dockerfile
    image: whisperhub-node
    container_name: whisperhub-node
    restart: unless-stopped
    networks:
      - app-network

  scalarchatterbox:
    build:
      context: .
      dockerfile: Dockerfile
    image: scalarchatterbox-node
    container_name: scalarchatterbox-node
    restart: unless-stopped
    networks:
      - app-network

  webserver:
    build:
      context: ./nginx-certbot
      dockerfile: Dockerfile
    image: nginx-certbot
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot-etc:/etc/letsencrypt
      - dhparam:/etc/ssl/certs
      - ${PWD}/config.yaml:/opt/nginx-certbot/config.yaml
    depends_on:
      - whisperhub
      - scalarchatterbox
    networks:
      - app-network

volumes:
  certbot-etc:
    driver: local
    driver_opts:
      type: none
      device: ./letsencrypt/
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: ./dhparam/
      o: bind

networks:
  app-network:
    driver: bridge
